CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS FACT;


CREATE TABLE IF NOT EXISTS STAGING.ORDERS (
    ID VARCHAR PRIMARY KEY,
    CREATED_DATE VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_PRODUCTS VARCHAR,
    ORDER_QUANTITY VARCHAR
);

CREATE TABLE IF NOT EXISTS FACT.ORDERS (
    ID VARCHAR PRIMARY KEY,
    CREATED_DATE TIMESTAMP,
    CUSTOMER_ID VARCHAR,
    FULL_ADDRESS VARCHAR,
    STREET_NUMBER VARCHAR,
    STREET_NAME VARCHAR,
    CITY VARCHAR,
    POSTCODE VARCHAR,
    STATE VARCHAR,
    COST FLOAT
);

CREATE TABLE IF NOT EXISTS FACT.ORDER_LINE AS (
    ID VARCHAR,
    CREATED_DATE TIMESTAMP,
    CUSTOMER_ID VARCHAR,
    PRODUCT VARCHAR,
    QUANTITY INT,
    VALUE FLOAT
)

CREATE TABLE IF NOT EXISTS STAGING.CUSTOMER (
    ID VARCHAR PRIMARY KEY,
    CREATED_TIME VARCHAR,
    FULL_NAME VARCHAR,
    SALUTATOIN VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    FULL_ADDRESS VARCHAR,
    STREET_NUMBER VARCHAR,
    STREET_NAME VARCHAR,
    CITY VARCHAR,
    POSTCODE VARCHAR,
    STATE VARCHAR

);

CREATE TABLE IF NOT EXISTS FACT.CUSTOMER (
    ID VARCHAR PRIMARY KEY,
    CREATED_TIME TIMESTAMP,
    FULL_NAME VARCHAR,
    SALUTATOIN VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    FULL_ADDRESS VARCHAR,
    STREET_NUMBER INT,
    STREET_NAME VARCHAR,
    CITY VARCHAR,
    POSTCODE VARCHAR,
    STATE VARCHAR
);


