red_pandas_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: admin
      password: admin
      dbname: eccom_db
      schema: public
      threads: 4
